# Generated by Django 5.0 on 2024-01-06 06:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='friend_requests',
        ),
        migrations.AddField(
            model_name='profile',
            name='friend_requests_received',
            field=models.ManyToManyField(blank=True, related_name='friend_requests_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='friend_requests_sent',
            field=models.ManyToManyField(blank=True, related_name='friend_requests_sent', to=settings.AUTH_USER_MODEL),
        ),
    ]
